/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './scaffold.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './scaffold.component.scss.shim';
const nodeDebugInfos_ScaffoldComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.ScaffoldComponent],import1.ScaffoldComponent,{})];
var renderType_ScaffoldComponent_Host:import2.RenderComponentType = (null as any);
class _View_ScaffoldComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _ScaffoldComponent_0_4:import1.ScaffoldComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScaffoldComponent_Host0,renderType_ScaffoldComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScaffoldComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('scaffold',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScaffoldComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScaffoldComponent_0_4 = new import1.ScaffoldComponent();
    this._appEl_0.initComponent(this._ScaffoldComponent_0_4,[],compView_0);
    compView_0.create(this._ScaffoldComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.ScaffoldComponent) && (0 === requestNodeIndex))) { return this._ScaffoldComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScaffoldComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ScaffoldComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_ScaffoldComponent_Host === (null as any))) { (renderType_ScaffoldComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ScaffoldComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScaffoldComponentNgFactory:import10.ComponentFactory<import1.ScaffoldComponent> = new import10.ComponentFactory<import1.ScaffoldComponent>('scaffold',viewFactory_ScaffoldComponent_Host0,import1.ScaffoldComponent);
const styles_ScaffoldComponent:any[] = [import11.styles];
const nodeDebugInfos_ScaffoldComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_ScaffoldComponent:import2.RenderComponentType = (null as any);
class _View_ScaffoldComponent0 extends import3.DebugAppView<import1.ScaffoldComponent> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScaffoldComponent0,renderType_ScaffoldComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScaffoldComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'Hello World!',this.debug(1,0,4));
    this.init([],[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_ScaffoldComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.ScaffoldComponent> {
  if ((renderType_ScaffoldComponent === (null as any))) { (renderType_ScaffoldComponent = viewUtils.createRenderComponentType('C:/Users/poli/Desarrollo/Workspaces/wkANGULAR2/angular2-component-webpack/src/scaffold.component.html',0,import9.ViewEncapsulation.Emulated,styles_ScaffoldComponent,{})); }
  return new _View_ScaffoldComponent0(viewUtils,parentInjector,declarationEl);
}